### ISSUE TITLE
MMDLib Version 1.0.0-rc1.25 Crash

### ISSUE THREAD

**Issue by Pengu-Hunter** [MinecraftModDevelopmentMods/MMDLib#22]
Both of the following crashes occur regardless of forge version and the only difference is the Base Metals Version.
[crash-2019-04-14_16.24.51-client.txt](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/3077071/crash-2019-04-14_16.24.51-client.txt)
[crash-2019-04-14_16.28.43-client.txt](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/3077076/crash-2019-04-14_16.28.43-client.txt)

**Comment by DatrixTHLK** [comment]
Same for me: https://paste.dimdev.org/owutataleb.mccrash

**Comment by dshadowwolf** [comment]
@Pengu-Hunter @DatrixTHLK the issue appears to be that, for some reason, EndMetals didn't get pushed out despite me having thought it did. We're fixing that right now. Thanks for the report.

**Comment by dshadowwolf** [comment]
As a note... at this point (and in general)... don't mix different -beta/-rc versions - while we generally don't make breaking changes, sometimes we do have to do it and that is usually exposed at a change of release spec (like -beta6 to -beta7 for BaseMetals really broke some things)

**Comment by Pengu-Hunter** [comment]
Noted it was just an atempt to fin a fix and not something i normally do unless there is a problem using the intended versions together, and thank you for the response and explanation about the crash.

**Comment by dshadowwolf** [comment]
...apparently there was a bug somewhere that was causing gradle to say "oh, they've told me to run the task that uploads stuff to CurseForge, but thats not needed - that task is already up to date"... Sorry about that, folks.

**Comment by DatrixTHLK** [comment]
It's alright, that happens. I'm just happy for a response, I appreciate it!
