### ISSUE TITLE
[1.12.2] Severe problem during mod loading that caused the game to fail

### ISSUE THREAD

**Issue by Spearkiller** [MinecraftModDevelopmentMods/MMDLib#23]
Updated all my MMD mods (Nether Metals, End Metals, etc) and found that they needed MMDlib to work now. Installed it, and now get a fatal error that causes the game to crash.

https://pastebin.com/86JwCxfJ

Thought it must be an error with this mod; going back a constructs armory version and the error still persists, but worked before I updated all these mods. (by the looks of things its these two mods causing the errors and MMDlib is the one catching the exception, so hopefully here's the right place)

**Comment by dshadowwolf** [comment]
@YaibaToKen This is your field - you've got something going sideways in the Constructs' Armory code and it didn't get caught because I f*cked up and forgot to have it in my test setup.

**Comment by dshadowwolf** [comment]
(Wait... I've not yet been unable to reproduce - will keep trying, give me a few)

**Comment by dshadowwolf** [comment]
...I cannot reproduce this at all.

**Comment by YaibaToKen** [comment]
@Spearkiller could I bother you to reproduce this with only Tinker's Construct, Construct's Armory, Base Metals and their dependencies? Latest versions if possible.

**Comment by dshadowwolf** [comment]
I have tried several times with various collections of mods to make this happen, both pure client and pure server. I cannot reproduce this bug. This appears to be a mod-interaction issue and without a reliable way to reproduce, there is little we can do.

**Comment by Spearkiller** [comment]
It worked fine when it was just those mods. Installed all the others and it crashed again. Deleted all configs, and it still crashed. Went into BaseMetals.cfg and changed conarm_integration to false and now it works. And I still have Base Metals materials for constructs armors, so.... yeah. I guess it's fixed now.

**Comment by dshadowwolf** [comment]
I wish I knew what was causing this - I tried a wide selection of the mods listed in the log and could not reproduce (though I did find a different bug during the testing, yay!)

**Comment by YaibaToKen** [comment]
Pretty sure the reason you got the materials even though you disabled the `conarm_integration` is because of `Armory Expansion` though.

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/98733229df9db7c65677911136b4eaf7

I can shed some light onto the issue. Try adding two mods that add the same materials. @YaibaToKen is it possible for MMD lib to just add a copy of the material with a -2 at the end? It seems many mods like duplicating materials but the textures etc are different.

**Comment by YaibaToKen** [comment]
@P3rf3ctXZer0 that crash happens because I'm an idiot and forgot to double check if I could register those stats when coding Armory Expansion. Does that still happen in version 1.3.0 of the mod?

**Comment by P3rf3ctXZer0** [comment]
Checking now. - Wait I don't see that version ... Was it just uploaded - can I get the jar directly? - For 1.12.2 I only see https://minecraft.curseforge.com/projects/mmdlib/files @YaibaToKen

**Comment by YaibaToKen** [comment]
Armory Expansion is its own mod:
https://minecraft.curseforge.com/projects/armory-expansion/files/2714057

**Comment by P3rf3ctXZer0** [comment]
Oh **** I miss read the comment ... sorry it has been a busy day

**Comment by dshadowwolf** [comment]
@YaibaToKen is this still valid ?

**Comment by YaibaToKen** [comment]
I haven't been able to test, but lemme check real quick if Armory Expansion will crash with the latest versions of MMD mods

**Comment by YaibaToKen** [comment]
nope, no crash using latest (1.3.0 as of writing this)
