### ISSUE TITLE
MMDLib 1.12 Recipe Bug

### ISSUE THREAD

**Issue by Pengu-Hunter** [MinecraftModDevelopmentMods/MMDLib#24]
MMDLib recipe charcoal nuggets to charcoal only takes 6 nuggets but charcoal makes 9 nuggets, if it's not a bug I'll say no more, but i thought you should know.

**Comment by dshadowwolf** [comment]
...okay, sounds like a typo in the json - considering there are a few other minor fixes queued, I'll see about another CF release covering this
