### ISSUE TITLE
armor bug 1.12.2

### ISSUE THREAD

**Issue by andrewq99** [MinecraftModDevelopmentMods/MMDLib#28]
when i put obsidian armor and quartz armor on me and on armor stand this is what happens 
![1](https://user-images.githubusercontent.com/39251943/57427913-0157c900-71f4-11e9-9453-e09e07a36f4d.jpg)

**Comment by andrewq99** [comment]
and where is redstone armor and lapis armor

**Comment by dshadowwolf** [comment]
I think this is already fixed, but let me do some testing...

**Comment by dshadowwolf** [comment]
...found a different bug... dammit all

**Comment by dshadowwolf** [comment]
okay, yeah - was a set of missing textures... fixed soon-ish in dev

**Comment by dshadowwolf** [comment]
believe this is fixed in -rc2 - closing
