### ISSUE TITLE
Server bug

### ISSUE THREAD

**Issue by VirgileFullP4** [MinecraftModDevelopmentMods/MMDLib#29]
Hey, I was trying to create an 1.12.2 modded server with the mod baseMetals that need this mod and when I launch the server it crashes. I don"t know how to deal with it. Thank you if you can find the answer.
[crash-2019-05-11_12.48.18-server.txt](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/3168938/crash-2019-05-11_12.48.18-server.txt)

**Comment by dshadowwolf** [comment]
🤦‍♂ I thought we'd gotten all of those. It comes from Java having idiocy in the "Float.parseFloat" routine where it doesn't understand anything other than the English decimal-point. Fixed locally - will be part of -rc2. Workaround can be found in the BaseMetals Issue Tracker... see https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/407 - I believe this covers the workaround.

**Comment by dshadowwolf** [comment]
This issue should be resolved as of the release of -rc2 - closing
