### ISSUE TITLE
Conflict with metallugy 4 reforged and MMDlib.

### ISSUE THREAD

**Issue by hazerddex** [MinecraftModDevelopmentMods/MMDLib#44]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LMRECoremod (LittleMaidMob-Mod-1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  midnight (themidnight-0.3.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.7-core.jar)
  FarseekCoreMod (Farseek-1.12-2.3.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/15/19 12:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Metallurgy 4: Reforged (metallurgy)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Stats to "adamantine": Stats of type "core" were already registered by MMDLib. Use the events to modify stats.
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:951)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:232)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:208)
	at it.hurts.metallurgy_reforged.integration.mods.IntegrationCArmory.preInit(IntegrationCArmory.java:36)
	at it.hurts.metallurgy_reforged.Metallurgy.preInit(Metallurgy.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 835537176 bytes (796 MB) / 1946157056 bytes (1856 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 114 mods loaded, 114 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                              | Version                  | Source                                               | Signature                                |
	|:----- |:------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                       | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LCH   | mcp                             | 9.42                     | minecraft.jar                                        | None                                     |
	| LCH   | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                           | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ivtoolkit                       | 1.3.3-1.12               | minecraft.jar                                        | None                                     |
	| LCH   | OldModelLoader                  | 8.1.4.132                | minecraft.jar                                        | None                                     |
	| LCH   | dsurroundcore                   | 3.5.4.3                  | minecraft.jar                                        | None                                     |
	| LCH   | swordskillsapi                  | 1.1.0                    | 1.12.2-SwordSkillsApi-1.1.0.jar                      | None                                     |
	| LCH   | dynamicswordskills              | 1.12.2-6.0.1             | 1.12.2-DynamicSwordSkills-6.0.1.jar                  | None                                     |
	| LCH   | abyssalcraft                    | 1.9.8                    | AbyssalCraft-1.12.2-1.9.8.jar                        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | ctm                             | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
	| LCH   | chisel                          | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| LCH   | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCH   | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LCH   | thaumcraft                      | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
	| LCH   | twilightforest                  | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar          | None                                     |
	| LCH   | tconstruct                      | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                     | None                                     |
	| LCH   | acintegration                   | 1.8.1                    | AbyssalCraft+Integration-1.12.2-1.8.1.jar            | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | orbis-lib                       | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build78.jar                   | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether                          | 0.2.1                    | aether_ii-1.12.2-0.2.1+build78-universal.jar         | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | biomesoplenty                   | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar        | None                                     |
	| LCH   | botania                         | r1.10-361                | Botania+r1.10-361.jar                                | None                                     |
	| LCH   | craftstudioapi                  | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar   | None                                     |
	| LCH   | harvestcraft                    | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| LCH   | animania                        | 1.6.2                    | animania-1.12.2-1.6.2.jar                            | None                                     |
	| LCH   | antiqueatlas                    | 4.5.1                    | antiqueatlas-1.12.2-4.5.1.jar                        | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCH   | antiqueatlasoverlay             | 1.2                      | antiqueatlas-1.12.2-4.5.1.jar                        | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCH   | ebwizardry                      | 4.1.4                    | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar       | None                                     |
	| LCH   | arcane_essentials               | 1.0                      | Arcane+Essentials-0.9.jar                            | None                                     |
	| LCH   | conarm                          | 1.2.4                    | conarm-1.12.2-1.2.4.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | armoryexpansion                 | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
	| LCH   | armoryexpansion-custommaterials | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
	| LCH   | llibrary                        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                      | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                          | None                                     |
	| LCH   | armoryexpansion-iceandfire      | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
	| LCH   | armoryexpansion-matteroverdrive | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
	| LCH   | astikorcarts                    | 1.12.2-0.1.2.7           | astikorcarts-1.12.2-0.1.2.7.jar                      | None                                     |
	| LCH   | astralsorcery                   | 1.10.19                  | astralsorcery-1.12.2-1.10.19.jar                     | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | atum                            | 2.0.9                    | Atum-1.12.2-2.0.9.jar                                | None                                     |
	| LCH   | mmdlib                          | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                         | None                                     |
	| LCH   | basemetals                      | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | baseminerals                    | 2.5.0-rc2                | BaseMinerals-1.12-2.5.0-rc2.69.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | hammercore                      | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | botanicadds                     | 3r                       | BotanicAdditions-1.12.2-3r.jar                       | None                                     |
	| LCH   | carryon                         | 1.12.1                   | CarryOn+MC1.12.2+v1.12.1.jar                         | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCH   | chameleon                       | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| LCH   | extendedrenderer                | v1.0                     | coroutil-1.12.1-1.2.31.jar                           | None                                     |
	| LCH   | coroutil                        | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                           | None                                     |
	| LCH   | configmod                       | v1.0                     | coroutil-1.12.1-1.2.31.jar                           | None                                     |
	| LCH   | desirepaths                     | 1.12.1-1.2.8             | desirepaths-1.12.1-1.2.8.jar                         | None                                     |
	| LCH   | dynamictrees                    | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5.jar                        | None                                     |
	| LCH   | dynamictreesbop                 | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e.jar                    | None                                     |
	| LCH   | dynamictreesphc                 | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar                     | None                                     |
	| LCH   | dynamictreestc                  | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                     | None                                     |
	| LCH   | net.blacklab.lib                | 6.1.5.8                  | EBlib-1.12.2.jar                                     | None                                     |
	| LCH   | mysticalmechanics               | 0.8-hotfix               | Mystical+Mechanics-0.8-hotfix.jar                    | None                                     |
	| LCH   | embers                          | 1.13-hotfix2             | EmbersRekindled-1.13-hotfix2.jar                     | None                                     |
	| LCH   | erebus                          | 1.0.29                   | Erebus-1.0.29.jar                                    | None                                     |
	| LCH   | farseek                         | 2.3.2                    | Farseek-1.12-2.3.2.jar                               | None                                     |
	| LCH   | grapplemod                      | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                          | None                                     |
	| LCH   | grimoireofgaia                  | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                   | None                                     |
	| LCH   | guideapi                        | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                          | None                                     |
	| LCH   | hw_inv                          | 1.12.1-1.1.9             | hostileworlds_invasions-1.12.1-1.1.9.jar             | None                                     |
	| LCH   | hungeringdarkness               | 1.2.1                    | Hungering+Darkness-1.12.2-1.2.1.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | improvableskills                | 3.6.3r                   | ImprovableSkills-1.12.2-3.6.3r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | infernalmobs                    | 1.7.6                    | InfernalMobs-1.12.1.jar                              | None                                     |
	| LCH   | instantunify                    | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                        | None                                     |
	| LCH   | lex                             | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                               | None                                     |
	| LCH   | lmreengaged                     | 8.1.4.132                | LittleMaidMob-Mod-1.12.2.jar                         | None                                     |
	| LCH   | lycanitesmobs                   | 2.0.0.0 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.0.0.jar                     | None                                     |
	| LCH   | mca                             | 6.0.0-beta               | MCA-1.12.2-6.0.0-beta-universal.jar                  | None                                     |
	| LCE   | metallurgy                      | 0.2.0                    | Metallurgy-4-Reforged-0.2.0.jar                      | None                                     |
	| LC    | modernmetals                    | 2.5.0-rc2                | ModernMetals-1.12-2.5.0-rc2.152.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | mystcraft                       | 0.13.7.03                | mystcraft-1.12.2-0.13.7.03.jar                       | None                                     |
	| LC    | moremystcraft                   | 0.5.6                    | moremystcraft-1.12.2-0.5.6.jar                       | None                                     |
	| LC    | moveplus                        | 1.12.1-2.4.6             | moveplus-1.12.1-2.4.6.jar                            | None                                     |
	| LC    | mowziesmobs                     | 1.5.4                    | mowziesmobs-1.5.4.jar                                | None                                     |
	| LC    | multimob                        | 1.0.5                    | multimob-1.0.5.jar                                   | None                                     |
	| LC    | naturescompass                  | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                      | None                                     |
	| LC    | neat                            | 1.4-17                   | Neat+1.4-17.jar                                      | None                                     |
	| LC    | nex                             | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                            | None                                     |
	| LC    | orespawn                        | 3.3.1                    | OreSpawn-1.12-3.3.1.172.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | pages                           | 1.3.3                    | pages-1.12.2-1.3.3.jar                               | None                                     |
	| LC    | plustic                         | 7.0.7.0                  | plustic-7.0.7.0.jar                                  | None                                     |
	| LC    | primitivemobs                   | 1.2.3a                   | primitivemobs-1.2.3a.jar                             | None                                     |
	| LC    | reccomplex                      | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                         | None                                     |
	| LC    | additionalstructures            | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar     | None                                     |
	| LC    | roots                           | 0.104                    | roots-2-0.104.jar                                    | None                                     |
	| LC    | silentlib                       | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                      | None                                     |
	| LC    | scalinghealth                   | 1.3.37                   | ScalingHealth-1.12.2-1.3.37+142.jar                  | None                                     |
	| LC    | sereneseasons                   | 1.2.16                   | SereneSeasons-1.12.2-1.2.16-universal.jar            | None                                     |
	| LC    | flammpfeil.slashblade           | mc1.12-r25               | SlashBlade-mc1.12-r25.jar                            | None                                     |
	| LC    | slashbladetic                   | V1.0.8-MC1.12.2          | SlashBladeTic-V1.0.8-MC1.12.2.jar                    | None                                     |
	| LC    | storagedrawers                  | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                      | None                                     |
	| LC    | streams                         | 0.4.7                    | Streams-1.12-0.4.7.jar                               | None                                     |
	| LC    | taiga                           | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                               | None                                     |
	| LC    | tcinventoryscan                 | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar           | None                                     |
	| LC    | thaumicperiphery                | 0.3.0                    | thaumicperiphery-0.3.0.jar                           | None                                     |
	| LC    | beneath                         | 1.5.1                    | The+Beneath-1.12.2-1.5.1.jar                         | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LC    | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
	| LC    | tombstone                       | 3.5.3                    | tombstone-3.5.3-1.12.jar                             | None                                     |
	| LC    | tropicraft                      | 7.1.9.115                | tropicraft-MC1.12.2-7.1.9.115.jar                    | None                                     |
	| LC    | tumbleweed                      | 1.11-0.4.5               | tumbleweed-1.11-0.4.5.jar                            | None                                     |
	| LC    | vc                              | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                          | None                                     |
	| LC    | waystones                       | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                          | None                                     |
	| LC    | weather2                        | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12.jar                           | None                                     |
	| LC    | zombieawareness                 | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar                   | None                                     |
	| LC    | phosphor-lighting               | 1.12.2-0.2.4             | phosphor-1.12.2-0.2.4+build46.jar                    | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LC    | orelib                          | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround                       | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | immersiveengineering            | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | thebetweenlands                 | 3.4.7                    | TheBetweenlands-3.4.7-universal.jar                  | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LC    | midnight                        | 0.3.4                    | themidnight-0.3.4.jar                                | None                                     |
	| LC    | armoryexpansion-conarm          | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |

	Loaded coremods (and transformers): 
LMRECoremod (LittleMaidMob-Mod-1.12.2.jar)
  net.blacklab.lmr.util.coremod.Transformer
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
midnight (themidnight-0.3.4.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  
AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.7-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
FarseekCoreMod (Farseek-1.12-2.3.2.jar)
  farseek.core.FarseekClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.17' Renderer: 'GeForce RTX 2080/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 580 names; 476 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Botanic Additions (botanicadds) @3r
    -Improvable Skills (improvableskills) @3.6.3r

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.17
	OpenGlRenderer: GeForce RTX 2080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by dshadowwolf** [comment]
this sounds like Metallurgy trying to handle TiCon integration for certain materials... I don't know of a good way to fix this but you could try turning off TiCon integration in MMDLib/BaseMetals/etc...

**Comment by Davoleo** [comment]
This is on metallurgy's side, it should be fixed in the next version
