### ISSUE TITLE
mmdlib exception

### ISSUE THREAD

**Issue by GhostZero91** [MinecraftModDevelopmentMods/MMDLib#48]
Can someone tell me what is wrong?
[crash-2019-08-15_20.18.54-server.txt](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/3506716/crash-2019-08-15_20.18.54-server.txt)

**Comment by faceofcat** [comment]
` java.lang.NumberFormatException: For input string: "0,02"`

you probably have a bad config file somewhere.

**Comment by GhostZero91** [comment]
Deleted the config folder
[crash-2019-08-16_18.30.29-server.txt](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/3510387/crash-2019-08-16_18.30.29-server.txt)

**Comment by dshadowwolf** [comment]
This is a bug triggered by Java having issues with inconsistency - it has internationalization (I18N) baked in everywhere except in Float.ParseFloat() - which requires the '.' to be used as a delimiter. This is, basically, a duplicate issue - see [BaseMetals #407](https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/407) for a workaround.
