### ISSUE TITLE
when i start my server it crashes after a bit

### ISSUE THREAD

**Issue by M0ld0** [MinecraftModDevelopmentMods/MMDLib#58]
this the crash report
[crash-2020-10-29_04.24.09-server.txt](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/5455770/crash-2020-10-29_04.24.09-server.txt)
How can i fix it?

**Comment by dshadowwolf** [comment]
Duplicates issue #55 and an even older BaseMetals issue - closing.

(See the resolution listed for issue #55 and please, check for existing issues before opening new ones)
