### ISSUE TITLE
Minecraft Mods server 1.12.2

### ISSUE THREAD

**Issue by Falky02** [MinecraftModDevelopmentMods/MMDLib#61]
qualche mod sui minerali ma che si possano fare armature e spade...  (oltre al rubino e allo smeraldo)

**Comment by Falky02** [comment]
(forge)

**Comment by Falky02** [comment]
(per chi ha messo la traduzione in italiano fucina in inglese)

**Comment by dshadowwolf** [comment]
I am unsure what, exactly, you are asking for or reporting - my grasp of Italian is very minimal and even using Google Translate to help me understand the parts that I had a lot of trouble with did not help.

I see "a mod that adds weapons and items" and "not just ruby and emerald" along with "for those that added translations in Italian". Is there an issue with the existing translation of one (or more) of the mods translations?

**Comment by Falky02** [comment]
I spoke very well in Italian, maybe it's google translator

**Comment by dshadowwolf** [comment]
No, its that I don't speak Italian very well - I was able to understand a couple of phrases on my own, and adding Google Translate to try and help me figure out how they went together didn't help me understand anything.

**Comment by Falky02** [comment]
I always speak to Italians and I was born there

**Comment by Falky02** [comment]
it could be that I wrote a word wrong and that's why you translated it as it shouldn't be

**Comment by Falky02** [comment]
so it could be that I was wrong

**Comment by Commoble** [comment]
The best I could parse that as was "not many mineral mods yet that can make armor and tools other than ruby and emerald", but I don't see what that has to do with this github

**Comment by dshadowwolf** [comment]
That was my question - I got roughly the same out of it and was wondering if this was a report of changes needed or what :)

**Comment by Falky02** [comment]
but then you understood what I said

**Comment by Commoble** [comment]
What exactly is the problem you are reporting?

**Comment by Falky02** [comment]
I have already solved
