### ISSUE TITLE
Problem client side

### ISSUE THREAD

**Issue by Maverick044** [MinecraftModDevelopmentMods/MMDLib#62]
So, I'm trying to setup a forge server using TiC, MMDlib, Base Metals, and Orespawn.. 

My server starts up just fine, but when I attempt to log into the server the client is rejected by the server saying 

Base metals requires version 2.5.0-cr2 but mod is not found on client
MMDlib requires version 1.0.0-cr2 but mod is not found on client
Orespawn requires version 3.3.1 but mod is not found on client

All 3 of the mod files are in my mod folder and they are the exact same versions that are on the server...

I am completely lost here since this makes no sense to me and I cannot find any info as to what may be causing this. any suggestions or help here would be greatly appreciated.

thanks and happy belated new year to you all
![Screenshot](https://user-images.githubusercontent.com/76850367/103445371-f8690600-4c27-11eb-93fc-aff1fcf1c121.jpg)
![Screenshot2](https://user-images.githubusercontent.com/76850367/103445398-50077180-4c28-11eb-8478-9b821e595390.jpg)

**Comment by dshadowwolf** [comment]
Odd, but... I've never seen "Mods" (capital "M") - always "mods" (lowercase "m") - and Minecraft (and, hence, Forge) is case sensitive about things like this.

**Comment by Maverick044** [comment]
I'll see if that is an issue... oddly, when I check the loaded mods in game, neither of the 3 mentioned mods are listing

Update: changing the capital M to lowercase did not solve the problem sadly... the game itself is installed in a custom directory on my machine since I do not keep anything other than my OS on my main drive hence the "M" in minecraft.. but I doubt that the mods would fail to function because they are not in the default install directory on the C drive...

and I've hit a proverbial wall...

Update 2: Disregard... I figured out the problem... it was where I had copies of the mod files... *facepalm* should have thought about that... 

thank you for shaking the cobwebs out of my brain.. 

happy new year to you

**Comment by dshadowwolf** [comment]
No problem - I figured it was that the mods weren't being found - took a guess with the folder name. Glad my guess did help find the problem, though.
