### ISSUE TITLE
Crashes with Base Minerals and Base Metals

### ISSUE THREAD

**Issue by SkyfireGaming** [MinecraftModDevelopmentMods/MMDLib#66]
For some reason my game crashes whenever I try to launch Base Minerals and Base Metals on Forge, both of which require MMDLib to run. I would provide a latest.log but it crashes before I can open it.

**Comment by KiriCattus** [comment]
Are you using the latest of all three mods? Is MMDLib installed? (That has happened before) and the crash log would do fine too if you have one of those?

**Comment by KiriCattus** [comment]
I'm closing this issue as invalid due to no crash logs or reply from the author.
