### ISSUE TITLE
MMDLib is crashing my server on startup

### ISSUE THREAD

**Issue by caffeineLover** [MinecraftModDevelopmentMods/MMDLib#72]
Running
- minecraft_server.1.12.2.jar
- forge-1.12.2-14.23.5.2855.jar

When I add MMDLib-1.12-1.0.0-rc2.36.jar to the mods/ folder, the server stops loading and quits.   When I remove this file, the server startup completes and I can play.  I'm new to MC Forge, but am a sophisticated user, so please feel free to reach out.  I'd really like to get mod working very much.

From the stacktrace it almost looks like kotlin is a dependency?   Not sure what kotlin is.

[debug.log](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/6870802/debug.log)
[latest.log](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/6870806/latest.log)

**Comment by dshadowwolf** [comment]
MMDLib has zero Kotlin in it and should not be having any effect on any code that is not MMDLib - and if you are not using any of the *Metals mods, then there should be no need to use it at all, as it will have zero effect on anything. MMDLib is like CoFHCore in that its a lot of support for other mods, nothing for itself. 

If you can provide more information about your setup so we can try and replicate this crash we'd be grateful, as it is odd that pure Java code is causing a crash in Kotlin...

**Comment by caffeineLover** [comment]
I'm so sorry.   I've been diagnosing this, and I _swear_ the problem exhibited when I added MMDLib and vanished when I removed it.  But... I can't seem to reproduce now, so I must have been mistaken.  Really sorry about that.

I'll close the report.
