### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [MinecraftModDevelopmentMods/MMDLib#75]
Add the option to configure MMDLib settings from inside Minecraft mods menu and descriptions for each setting. Especially to understand what is fallback generator.

**Comment by dshadowwolf** [comment]
No.

If you don't understand  the name, then at least understand this:  It is a nearly useless, as simple as possible chunk of code to stop people from complaining about "Ores Aren't Generating" when they ignore the requirement for MMD OreSpawn or CoFHWorld or another ore generating mod to be installed and configured.

_NOTHING_ in MMDLib or the mods that utilize it can be safely configured from ***INSIDE*** the game - so there is ***ZERO*** point to having them have a configuration menu or screen when the game is actually running.
